//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heath.Lister.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heath.Lister.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete all.
        /// </summary>
        public static string CompleteAllText {
            get {
                return ResourceManager.GetString("CompleteAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string CompletedText {
            get {
                return ResourceManager.GetString("CompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string CompleteText {
            get {
                return ResourceManager.GetString("CompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this item?.
        /// </summary>
        public static string DeleteItemMessage {
            get {
                return ResourceManager.GetString("DeleteItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete these items?.
        /// </summary>
        public static string DeleteItemsMessage {
            get {
                return ResourceManager.GetString("DeleteItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this list? All items in this list will be deleted as well..
        /// </summary>
        public static string DeleteListMessage {
            get {
                return ResourceManager.GetString("DeleteListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDateText {
            get {
                return ResourceManager.GetString("DueDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string DueText {
            get {
                return ResourceManager.GetString("DueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Time.
        /// </summary>
        public static string DueTimeText {
            get {
                return ResourceManager.GetString("DueTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HighText {
            get {
                return ResourceManager.GetString("HighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomplete.
        /// </summary>
        public static string IncompleteText {
            get {
                return ResourceManager.GetString("IncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item details.
        /// </summary>
        public static string ItemDetailsText {
            get {
                return ResourceManager.GetString("ItemDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set reminder.
        /// </summary>
        public static string ItemReminderText {
            get {
                return ResourceManager.GetString("ItemReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string ItemText {
            get {
                return ResourceManager.GetString("ItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string ListText {
            get {
                return ResourceManager.GetString("ListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LowText {
            get {
                return ResourceManager.GetString("LowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumText {
            get {
                return ResourceManager.GetString("MediumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no items.
        /// </summary>
        public static string NoItemsText {
            get {
                return ResourceManager.GetString("NoItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no notes.
        /// </summary>
        public static string NoNotesText {
            get {
                return ResourceManager.GetString("NoNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not due.
        /// </summary>
        public static string NotDueText {
            get {
                return ResourceManager.GetString("NotDueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesText {
            get {
                return ResourceManager.GetString("NotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueText {
            get {
                return ResourceManager.GetString("OverdueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStartText {
            get {
                return ResourceManager.GetString("PinToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityText {
            get {
                return ResourceManager.GetString("PriorityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string RemainingText {
            get {
                return ResourceManager.GetString("RemainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date.
        /// </summary>
        public static string ReminderDateText {
            get {
                return ResourceManager.GetString("ReminderDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reminder will be set for {0}.
        ///
        ///(Set a Due Date and Due Time to get a more accurate reminder.).
        /// </summary>
        public static string ReminderMessageText {
            get {
                return ResourceManager.GetString("ReminderMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string ReminderText {
            get {
                return ResourceManager.GetString("ReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Time.
        /// </summary>
        public static string ReminderTimeText {
            get {
                return ResourceManager.GetString("ReminderTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Color.
        /// </summary>
        public static string TileColorText {
            get {
                return ResourceManager.GetString("TileColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayText {
            get {
                return ResourceManager.GetString("TodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
